language: php
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then composer require --dev phpstan/phpstan; fi
  - composer dump-autoload -o

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/phpstan analyse src/ --level=max; fi
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/php-coveralls -v --exclude-no-stmt; fi

notifications:
    email: false
